apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xpsbf1uhq-python 
  janus-idp.io/tekton: xpsbf1uhq-python
  backstage.io/kubernetes-id: xpsbf1uhq-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xpsbf1uhq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml