apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xpsbf1uhq-python-gitops
  description: This is GitOps manifest for xpsbf1uhq-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xpsbf1uhq-python
    backstage.io/kubernetes-id: xpsbf1uhq-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xpsbf1uhq-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xpsbf1uhq-python
